export const NEW_DATA_REQUEST = "NEW_DATA_REQUEST"
export const NEW_DATA_SUCCESS = "NEW_DATA_SUCCESS"
export const NEW_DATA_RESET   = "NEW_DATA_RESET"; 
export const NEW_DATA_FAIL    = "NEW_DATA_FAIL"; 

export const GET_DATA_REQUEST = "GET_DATA_REQUEST"
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS"
export const GET_DATA_RESET   = "GET_DATA_RESET"; 
export const GET_DATA_FAIL    = "GET_DATA_FAIL"; 

export const DELETE_DATA_REQUEST = "DELETE_DATA_REQUEST"
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS"
export const DELETE_DATA_RESET   = "DELETE_DATA_RESET"; 
export const DELETE_DATA_FAIL    = "DELETE_DATA_FAIL"; 

export const UPDATE_DATA_REQUEST = "UPDATE_DATA_REQUEST"
export const UPDATE_DATA_SUCCESS = "UPDATE_DATA_SUCCESS"
export const UPDATE_DATA_RESET   = "UPDATE_DATA_RESET"; 
export const UPDATE_DATA_FAIL    = "UPDATE_DATA_FAIL"; 

export const DETAILS_DATA_REQUEST = "DETAILS_DATA_REQUEST"
export const DETAILS_DATA_SUCCESS = "DETAILS_DATA_SUCCESS"
export const DETAILS_DATA_RESET   = "UPDATE_DATA_RESET"; 
export const DETAILS_DATA_FAIL    = "DETAILS_DATA_FAIL";