export const R_NEW_DATA_REQUEST = "R_NEW_DATA_REQUEST"
export const R_NEW_DATA_SUCCESS = "R_NEW_DATA_SUCCESS"
export const R_NEW_DATA_RESET   = "R_NEW_DATA_RESET"; 
export const R_NEW_DATA_FAIL    = "R_NEW_DATA_FAIL"; 

export const R_GET_DATA_REQUEST = "R_GET_DATA_REQUEST"
export const R_GET_DATA_SUCCESS = "R_GET_DATA_SUCCESS"
export const R_GET_DATA_RESET   = "R_GET_DATA_RESET"; 
export const R_GET_DATA_FAIL    = "R_GET_DATA_FAIL"; 

export const R_DELETE_DATA_REQUEST = "R_DELETE_DATA_REQUEST"
export const R_DELETE_DATA_SUCCESS = "R_DELETE_DATA_SUCCESS"
export const R_DELETE_DATA_RESET   = "R_DELETE_DATA_RESET"; 
export const R_DELETE_DATA_FAIL    = "R_DELETE_DATA_FAIL"; 

export const R_UPDATE_DATA_REQUEST = "R_UPDATE_DATA_REQUEST"
export const R_UPDATE_DATA_SUCCESS = "R_UPDATE_DATA_SUCCESS"
export const R_UPDATE_DATA_RESET   = "R_UPDATE_DATA_RESET"; 
export const R_UPDATE_DATA_FAIL    = "R_UPDATE_DATA_FAIL"; 

export const R_DETAILS_DATA_REQUEST = "R_DETAILS_DATA_REQUEST"
export const R_DETAILS_DATA_SUCCESS = "R_DETAILS_DATA_SUCCESS"
export const R_DETAILS_DATA_RESET   = "R_UPDATE_DATA_RESET"; 
export const R_DETAILS_DATA_FAIL    = "R_DETAILS_DATA_FAIL";